### ISSUE TITLE
Oudtated vscode-ripgrep breaks extension

### ISSUE THREAD

**Issue by dmig** [fireyy/vscode-language-todo#3]
Trying to run 'List all TODOs' I get following error:

>Error: Command failed: "/home/dmig/.vscode-insiders/extensions/fireyy.vscode-language-todo-1.1.6/node_modules/vscode-ripgrep/bin/rg" --case-sensitive --line-number --column --hidden -e "(//|#|<!--|;|/*)\s*(TODO|FIXME|CHANGED|XXX|IDEA|HACK|NOTE|REVIEW|NB|BUG|QUESTION|COMBAK|TEMP|DEBUG|OPTIMIZE)"  -g "!**/node_modules/**" -g "!**/bower_components/**" -g "!**/.vscode/**" -g "!**/.github/**" -g "!**/.git/**" -g "!**/*.map" -g "!**/dist/**" -g "!**/venv/**"
>/bin/sh: 1: /home/dmig/.vscode-insiders/extensions/fireyy.vscode-language-todo-1.1.6/node_modules/vscode-ripgrep/bin/rg: Exec format error

Let's check why:
```sh
$ file /home/dmig/.vscode-insiders/extensions/fireyy.vscode-language-todo-1.1.6/node_modules/vscode-ripgrep/bin/rg
/home/dmig/.vscode-insiders/extensions/fireyy.vscode-language-todo-1.1.6/node_modules/vscode-ripgrep/bin/rg: Mach-O 64-bit x86_64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|WEAK_DEFINES|BINDS_TO_WEAK|PIE|HAS_TLV_DESCRIPTORS>
```
WTF?? What is 'Mach-O 64-bit x86_64 executable'?
The reason is in `package.json`:
```json
  "dependencies": {
    "vscode-ripgrep": "^0.6.0-patch.0.5"
  },
```
Outdated `vscode-ripgrep` is used. To fix this update dependency to latest.

To fix manually, edit `package.json`, change version string to:
```json
  "dependencies": {
    "vscode-ripgrep": ">0.6.0-patch.0.5"
  },
```
then issue `npm up` in plugin directory.

**Comment by fireyy** [comment]
Thank you, fix in 1.1.7
