### ISSUE TITLE
Unable to open linked files

### ISSUE THREAD

**Issue by onetrev** [fireyy/vscode-language-todo#4]
When I Ctrl + Click on a link in the generate ToDo file it doesn't work and VS Code chucks this error in the notification area:

_Unable to open '404.php': A system error occurred (UNKNOWN: unknown error, open '\\c:\websites\clogic\wp-content\themes\cl4\404.php')._

Anything I can do to help troubleshoot this let me know!

**Comment by fireyy** [comment]
try 1.2.1 :)

**Comment by onetrev** [comment]
Perfection!
