### ISSUE TITLE
Regex pattern doesn't work properly on some files

### ISSUE THREAD

**Issue by Zaczero** [fireyy/vscode-language-todo#5]
So basically I'm using a 3rd party code (PHPMailer) and I noticed that there are quire many TODOs that don't exist (you will understand when you look on the screenshot below).

![bug preview](https://i.imgur.com/Pqygp4k.png)

I see that many of them contains "debug" word however it's not a comment 😨
Test code: https://github.com/PHPMailer/PHPMailer/blob/master/src/SMTP.php

```
Regex:
(//|#|<!--|;|/*)\\s*(TODO|FIXME|CHANGED|XXX|IDEA|HACK|NOTE|REVIEW|NB|BUG|QUESTION|COMBAK|TEMP|DEBUG|OPTIMIZE)
```

```
Executing:
C:\WINDOWS\system32\cmd.exe /d /s /c ""c:\Program Files\Microsoft VS Code\resources\app\node_modules.asar.unpacked\vscode-ripgrep\bin\rg.exe" --no-messages -H --column --line-number --color never --hidden -e "(//|#|<!--|;|/*)\s*(TODO|FIXME|CHANGED|XXX|IDEA|HACK|NOTE|REVIEW|NB|BUG|QUESTION|COMBAK|TEMP|DEBUG|OPTIMIZE)" -g "!**/node_modules/**" -g "!**/bower_components/**" -g "!**/.vscode/**" -g "!**/.github/**" -g "!**/.git/**" -g "!**/*.map" ."
````

---

Another example (jQuery):

![bug preview](https://i.imgur.com/dqtv1I8.png)

**Comment by fireyy** [comment]
try 1.2.2 :)

**Comment by Zaczero** [comment]
Confirming that it has been fixed 🤗🎉

![screenshot](https://prtsc.me/i/b47d4ea8.png)
