### ISSUE TITLE
Extension error reported in VS Code start up performance

### ISSUE THREAD

**Issue by onetrev** [fireyy/vscode-language-todo#7]
Not sure exactly why or what the issue is, but I was checking VS Code "Start Up Performance" and noticed this error in the screenshot below was being reported.

![capture error](https://user-images.githubusercontent.com/597601/42419846-019a3a12-8300-11e8-9c49-a347c4c7d27d.PNG)

**Comment by fireyy** [comment]
You can ignore this issue. vue-html is only support when you install [Vetur](https://marketplace.visualstudio.com/items?itemName=octref.vetur)

**Comment by onetrev** [comment]
Gotcha. Okay, thanks!
